/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import examclient.LoginPage;
import examclient.Person;
import java.awt.Component;

/**
 *
 * @author mariusz
 */
public final class ApplicationFrame extends javax.swing.JFrame {
    
    private static Person rola;

    /**
     * Creates new form ApplicationFrame
     */
    public ApplicationFrame() {
        initComponents();
        
        showPanel("LoginPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        serverAddress = new javax.swing.JTextField();
        serverPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logINButton = new javax.swing.JButton();
        StudentPanel = new javax.swing.JPanel();
        StudentButtonDoExam = new javax.swing.JButton();
        StudentButtonCheckResults = new javax.swing.JButton();
        StudentButtonLogOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TeacherPanel = new javax.swing.JPanel();
        TeacherButtonAddExam = new javax.swing.JButton();
        TeacherButtonCheckAnswears = new javax.swing.JButton();
        TeacherButtonLogOut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TeacherButtonAssignExam = new javax.swing.JButton();
        TeacherButtonViewAnswears = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        AdminButtonAddGroup = new javax.swing.JButton();
        AdminButtonAssignStudent = new javax.swing.JButton();
        AdminButtonLogOut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chooseRolePanel = new javax.swing.JPanel();
        choosePanelButtonAdmin = new javax.swing.JButton();
        choosePanelButtonTeacher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(780, 507));
        setMinimumSize(new java.awt.Dimension(780, 507));
        setPreferredSize(new java.awt.Dimension(780, 507));
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        LoginPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        LoginPanel.setName("LoginPanel"); // NOI18N
        LoginPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        serverAddress.setText("127.0.0.1");

        serverPort.setText("30000");

        jLabel1.setText("Adres serwera:");

        jLabel2.setText("Numer portu:");

        jLabel3.setText("Proszę podać login i hasło.");

        login.setToolTipText("");

        password.setToolTipText("Minimum 5 znaków");

        jLabel4.setText("Login:");

        jLabel5.setText("Hasło:");

        logINButton.setText("Zaloguj");
        logINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logINButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(serverAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(logINButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(serverAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logINButton))
        );

        getContentPane().add(LoginPanel, "card2");

        StudentPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        StudentPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        StudentPanel.setName("StudentPanel"); // NOI18N
        StudentPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        StudentButtonDoExam.setText("Rozwiąż egzamin");
        StudentButtonDoExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonDoExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonDoExamActionPerformed(evt);
            }
        });

        StudentButtonCheckResults.setText("Sprawdź wyniki");
        StudentButtonCheckResults.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonCheckResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonCheckResultsActionPerformed(evt);
            }
        });

        StudentButtonLogOut.setText("Wyloguj");
        StudentButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonLogOutActionPerformed(evt);
            }
        });

        jLabel6.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel7.setText("Panel Studenta");

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(541, 541, 541)
                .addComponent(StudentButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel6))
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(StudentButtonDoExam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(StudentButtonCheckResults, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(StudentButtonLogOut))
                .addGap(115, 115, 115)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentButtonDoExam)
                    .addComponent(StudentButtonCheckResults))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(StudentPanel, "card3");

        TeacherPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        TeacherPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        TeacherPanel.setName("TeacherPanel"); // NOI18N
        TeacherPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        TeacherButtonAddExam.setText("Dodaj egzamin");
        TeacherButtonAddExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonAddExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonAddExamActionPerformed(evt);
            }
        });

        TeacherButtonCheckAnswears.setText("Podlicz wyniki");
        TeacherButtonCheckAnswears.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonCheckAnswears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonCheckAnswearsActionPerformed(evt);
            }
        });

        TeacherButtonLogOut.setText("Wyloguj");
        TeacherButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonLogOutActionPerformed(evt);
            }
        });

        jLabel8.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel9.setText("Panel Egzaminatora");

        TeacherButtonAssignExam.setText("Przypisz egzamin grupie");
        TeacherButtonAssignExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonAssignExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonAssignExamActionPerformed(evt);
            }
        });

        TeacherButtonViewAnswears.setText("Sprawdź wyniki");
        TeacherButtonViewAnswears.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonViewAnswears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonViewAnswearsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeacherPanelLayout = new javax.swing.GroupLayout(TeacherPanel);
        TeacherPanel.setLayout(TeacherPanelLayout);
        TeacherPanelLayout.setHorizontalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addGap(510, 510, 510)
                .addComponent(TeacherButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel8))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(TeacherButtonAddExam, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TeacherButtonCheckAnswears, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(TeacherButtonAssignExam)
                .addGap(60, 60, 60)
                .addComponent(TeacherButtonViewAnswears, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TeacherPanelLayout.setVerticalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(TeacherButtonLogOut))
                .addGap(115, 115, 115)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherButtonAddExam)
                    .addComponent(TeacherButtonCheckAnswears))
                .addGap(50, 50, 50)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherButtonAssignExam)
                    .addComponent(TeacherButtonViewAnswears)))
        );

        getContentPane().add(TeacherPanel, "card4");

        AdminPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        AdminPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        AdminPanel.setName("AdminPanel"); // NOI18N
        AdminPanel.setPreferredSize(new java.awt.Dimension(779, 506));
        AdminPanel.setRequestFocusEnabled(false);

        AdminButtonAddGroup.setText("Dodaj grupę");
        AdminButtonAddGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAddGroupActionPerformed(evt);
            }
        });

        AdminButtonAssignStudent.setText("Przypisz studentów do grupy");
        AdminButtonAssignStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonAssignStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAssignStudentActionPerformed(evt);
            }
        });

        AdminButtonLogOut.setText("Wyloguj");
        AdminButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonLogOutActionPerformed(evt);
            }
        });

        jLabel10.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel11.setText("Panel Administratora");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(503, 503, 503)
                .addComponent(AdminButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel10))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(AdminButtonAddGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(AdminButtonAssignStudent))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addComponent(AdminButtonLogOut))
                .addGap(115, 115, 115)
                .addComponent(jLabel10)
                .addGap(50, 50, 50)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminButtonAddGroup)
                    .addComponent(AdminButtonAssignStudent)))
        );

        getContentPane().add(AdminPanel, "card5");

        chooseRolePanel.setName("chooseRolePanel"); // NOI18N

        choosePanelButtonAdmin.setText("Admin panel");
        choosePanelButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePanelButtonAdminActionPerformed(evt);
            }
        });

        choosePanelButtonTeacher.setText("Teacher panel");
        choosePanelButtonTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePanelButtonTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseRolePanelLayout = new javax.swing.GroupLayout(chooseRolePanel);
        chooseRolePanel.setLayout(chooseRolePanelLayout);
        chooseRolePanelLayout.setHorizontalGroup(
            chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseRolePanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(choosePanelButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(choosePanelButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        chooseRolePanelLayout.setVerticalGroup(
            chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseRolePanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosePanelButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choosePanelButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(chooseRolePanel, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logINButtonActionPerformed
        LoginPage.logIn(this);
    }//GEN-LAST:event_logINButtonActionPerformed

    private void choosePanelButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePanelButtonAdminActionPerformed
        showPanel("AdminPanel");
    }//GEN-LAST:event_choosePanelButtonAdminActionPerformed

    private void StudentButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonLogOutActionPerformed
        System.out.println(rola.logOut());
        showPanel("LoginPanel");
    }//GEN-LAST:event_StudentButtonLogOutActionPerformed

    private void TeacherButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonLogOutActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_TeacherButtonLogOutActionPerformed

    private void AdminButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonLogOutActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_AdminButtonLogOutActionPerformed

    private void choosePanelButtonTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePanelButtonTeacherActionPerformed
        showPanel("TeacherPanel");
    }//GEN-LAST:event_choosePanelButtonTeacherActionPerformed

    private void StudentButtonDoExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonDoExamActionPerformed
        System.out.println( Person.sendRequest("do_exam") );
    }//GEN-LAST:event_StudentButtonDoExamActionPerformed

    private void StudentButtonCheckResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonCheckResultsActionPerformed
        System.out.println( Person.sendRequest("check_results") );
    }//GEN-LAST:event_StudentButtonCheckResultsActionPerformed

    private void TeacherButtonAddExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonAddExamActionPerformed
        System.out.println( Person.sendRequest("add_exam") );
    }//GEN-LAST:event_TeacherButtonAddExamActionPerformed

    private void TeacherButtonCheckAnswearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonCheckAnswearsActionPerformed
        System.out.println( Person.sendRequest("check_answears") );
    }//GEN-LAST:event_TeacherButtonCheckAnswearsActionPerformed

    private void TeacherButtonAssignExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonAssignExamActionPerformed
        System.out.println( Person.sendRequest("assign_exam_to_group") );
    }//GEN-LAST:event_TeacherButtonAssignExamActionPerformed

    private void TeacherButtonViewAnswearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonViewAnswearsActionPerformed
        System.out.println( Person.sendRequest("view_results") );
    }//GEN-LAST:event_TeacherButtonViewAnswearsActionPerformed

    private void AdminButtonAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAddGroupActionPerformed
        System.out.println( Person.sendRequest("add_group") );
    }//GEN-LAST:event_AdminButtonAddGroupActionPerformed

    private void AdminButtonAssignStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAssignStudentActionPerformed
        System.out.println( Person.sendRequest("assign_to_group") );
    }//GEN-LAST:event_AdminButtonAssignStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplicationFrame().setVisible(true);
            }
        });
    }
    
    /**
     * Ustawia visibility panelu przekazanego w argumencie na true, reszty na false. 
     * 
     * @param name String: nazwa panelu.
     */
    public void showPanel(String name){
        Component[] comp = getContentPane().getComponents();
        
        for(Component c : comp ){
            if ( c.getName().equals(name) ) 
                c.setVisible(true);
            else
                c.setVisible(false);
        }
    }
    
    /**
     * 
     * @param p 
     */
    public void setRole(Person p){
        rola = p;
    }
    
    /**
     * 
     * @return 
     */
    public String getServerAddr(){
        return serverAddress.getText();
    }

    /**
     * 
     * @return 
     */
    public String getLogin() {
        return login.getText();
    }

    /**
     * 
     * @return 
     */
    public String getPassword() {
        return password.getText();
    }

    /**
     * 
     * @return 
     */
    public String getServerPort() {
        return serverPort.getText();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButtonAddGroup;
    private javax.swing.JButton AdminButtonAssignStudent;
    private javax.swing.JButton AdminButtonLogOut;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton StudentButtonCheckResults;
    private javax.swing.JButton StudentButtonDoExam;
    private javax.swing.JButton StudentButtonLogOut;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JButton TeacherButtonAddExam;
    private javax.swing.JButton TeacherButtonAssignExam;
    private javax.swing.JButton TeacherButtonCheckAnswears;
    private javax.swing.JButton TeacherButtonLogOut;
    private javax.swing.JButton TeacherButtonViewAnswears;
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.JButton choosePanelButtonAdmin;
    private javax.swing.JButton choosePanelButtonTeacher;
    private javax.swing.JPanel chooseRolePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logINButton;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField serverAddress;
    private javax.swing.JTextField serverPort;
    // End of variables declaration//GEN-END:variables
}
