/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

import examclient.Administrator;
import examclient.LoginPage;
import examclient.Person;
import examclient.Student;
import examclient.Teacher;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author mariusz
 */
public final class ApplicationFrame extends javax.swing.JFrame {
    
    private static Person rola;

    /**
     * Konstruktor. Inicjuje wszystkie komponenty GUI.
     */
    public ApplicationFrame() {
        initComponents();
        
        showPanel("LoginPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        serverAddress = new javax.swing.JTextField();
        serverPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logINButton = new javax.swing.JButton();
        StudentPanel = new javax.swing.JPanel();
        StudentButtonDoExam = new javax.swing.JButton();
        StudentButtonCheckResults = new javax.swing.JButton();
        StudentButtonLogOut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TeacherPanel = new javax.swing.JPanel();
        TeacherButtonAddExam = new javax.swing.JButton();
        TeacherButtonCheckAnswears = new javax.swing.JButton();
        TeacherButtonLogOut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TeacherButtonAssignExam = new javax.swing.JButton();
        TeacherButtonViewAnswears = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        AdminButtonAddGroup = new javax.swing.JButton();
        AdminButtonAssignStudent = new javax.swing.JButton();
        AdminButtonLogOut = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chooseRolePanel = new javax.swing.JPanel();
        choosePanelButtonAdmin = new javax.swing.JButton();
        choosePanelButtonTeacher = new javax.swing.JButton();
        AdminDodajGrupe = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        nazwaGrupy = new javax.swing.JTextField();
        sendNewGroupCredentials = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        AdminButtonLogOut1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        AdminPrzypiszStudentaGrupie = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        AdminButtonLogOut2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        listaStudentow = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        listaGrup = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        TeacherPrzypiszEgzaminGrupie = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        AdminButtonLogOut3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        listaEgzaminow = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        listaGrup1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        StudentWyniki = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaWynikiEgzaminow = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        TeacherWynikiStudentow = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaWynikiEgzaminow1 = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 507));
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        LoginPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        LoginPanel.setName("LoginPanel"); // NOI18N
        LoginPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        serverAddress.setText("127.0.0.1");

        serverPort.setText("30000");

        jLabel1.setText("Adres serwera:");

        jLabel2.setText("Numer portu:");

        jLabel3.setText("Proszę podać login i hasło.");

        login.setToolTipText("");

        password.setToolTipText("Minimum 5 znaków");

        jLabel4.setText("Login:");

        jLabel5.setText("Hasło:");

        logINButton.setText("Zaloguj");
        logINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logINButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(serverAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(logINButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(serverAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2))
                    .addComponent(serverPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4))
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5))
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(logINButton))
        );

        getContentPane().add(LoginPanel, "card2");

        StudentPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        StudentPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        StudentPanel.setName("StudentPanel"); // NOI18N
        StudentPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        StudentButtonDoExam.setText("Rozwiąż egzamin");
        StudentButtonDoExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonDoExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonDoExamActionPerformed(evt);
            }
        });

        StudentButtonCheckResults.setText("Sprawdź wyniki");
        StudentButtonCheckResults.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonCheckResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonCheckResultsActionPerformed(evt);
            }
        });

        StudentButtonLogOut.setText("Wyloguj");
        StudentButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        StudentButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentButtonLogOutActionPerformed(evt);
            }
        });

        jLabel6.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel7.setText("Panel Studenta");

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel7)
                .addGap(541, 541, 541)
                .addComponent(StudentButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel6))
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(StudentButtonDoExam, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(StudentButtonCheckResults, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(StudentButtonLogOut))
                .addGap(115, 115, 115)
                .addComponent(jLabel6)
                .addGap(50, 50, 50)
                .addGroup(StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentButtonDoExam)
                    .addComponent(StudentButtonCheckResults))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(StudentPanel, "card3");

        TeacherPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        TeacherPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        TeacherPanel.setName("TeacherPanel"); // NOI18N
        TeacherPanel.setPreferredSize(new java.awt.Dimension(779, 506));

        TeacherButtonAddExam.setText("Dodaj egzamin");
        TeacherButtonAddExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonAddExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonAddExamActionPerformed(evt);
            }
        });

        TeacherButtonCheckAnswears.setText("Podlicz wyniki");
        TeacherButtonCheckAnswears.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonCheckAnswears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonCheckAnswearsActionPerformed(evt);
            }
        });

        TeacherButtonLogOut.setText("Wyloguj");
        TeacherButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonLogOutActionPerformed(evt);
            }
        });

        jLabel8.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel9.setText("Panel Egzaminatora");

        TeacherButtonAssignExam.setText("Przypisz egzamin grupie");
        TeacherButtonAssignExam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonAssignExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonAssignExamActionPerformed(evt);
            }
        });

        TeacherButtonViewAnswears.setText("Sprawdź wyniki");
        TeacherButtonViewAnswears.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TeacherButtonViewAnswears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherButtonViewAnswearsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeacherPanelLayout = new javax.swing.GroupLayout(TeacherPanel);
        TeacherPanel.setLayout(TeacherPanelLayout);
        TeacherPanelLayout.setHorizontalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addGap(510, 510, 510)
                .addComponent(TeacherButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel8))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(TeacherButtonAddExam, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(TeacherButtonCheckAnswears, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(TeacherButtonAssignExam)
                .addGap(60, 60, 60)
                .addComponent(TeacherButtonViewAnswears, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TeacherPanelLayout.setVerticalGroup(
            TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(TeacherButtonLogOut))
                .addGap(115, 115, 115)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherButtonAddExam)
                    .addComponent(TeacherButtonCheckAnswears))
                .addGap(50, 50, 50)
                .addGroup(TeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherButtonAssignExam)
                    .addComponent(TeacherButtonViewAnswears)))
        );

        getContentPane().add(TeacherPanel, "card4");

        AdminPanel.setMaximumSize(new java.awt.Dimension(779, 506));
        AdminPanel.setMinimumSize(new java.awt.Dimension(779, 506));
        AdminPanel.setName("AdminPanel"); // NOI18N
        AdminPanel.setPreferredSize(new java.awt.Dimension(779, 506));
        AdminPanel.setRequestFocusEnabled(false);

        AdminButtonAddGroup.setText("Dodaj grupę");
        AdminButtonAddGroup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAddGroupActionPerformed(evt);
            }
        });

        AdminButtonAssignStudent.setText("Przypisz studenta do grupy");
        AdminButtonAssignStudent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonAssignStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonAssignStudentActionPerformed(evt);
            }
        });

        AdminButtonLogOut.setText("Wyloguj");
        AdminButtonLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonLogOutActionPerformed(evt);
            }
        });

        jLabel10.setText("Proszę wybrać jedną z poniższych funkcji:");

        jLabel11.setText("Panel Administratora");

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(503, 503, 503)
                .addComponent(AdminButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel10))
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(AdminButtonAddGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(AdminButtonAssignStudent))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminButtonLogOut)
                    .addComponent(jLabel11))
                .addGap(109, 109, 109)
                .addComponent(jLabel10)
                .addGap(50, 50, 50)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminButtonAddGroup)
                    .addComponent(AdminButtonAssignStudent)))
        );

        getContentPane().add(AdminPanel, "card5");

        chooseRolePanel.setName("chooseRolePanel"); // NOI18N

        choosePanelButtonAdmin.setText("Admin panel");
        choosePanelButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePanelButtonAdminActionPerformed(evt);
            }
        });

        choosePanelButtonTeacher.setText("Teacher panel");
        choosePanelButtonTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePanelButtonTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chooseRolePanelLayout = new javax.swing.GroupLayout(chooseRolePanel);
        chooseRolePanel.setLayout(chooseRolePanelLayout);
        chooseRolePanelLayout.setHorizontalGroup(
            chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseRolePanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(choosePanelButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(choosePanelButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        chooseRolePanelLayout.setVerticalGroup(
            chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chooseRolePanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(chooseRolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosePanelButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choosePanelButtonTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        getContentPane().add(chooseRolePanel, "card6");

        AdminDodajGrupe.setMaximumSize(new java.awt.Dimension(779, 506));
        AdminDodajGrupe.setMinimumSize(new java.awt.Dimension(779, 506));
        AdminDodajGrupe.setName("adminDodajGrupe"); // NOI18N

        jLabel12.setText("Nazwa grupy:");

        nazwaGrupy.setToolTipText("");

        sendNewGroupCredentials.setText("Dodaj");
        sendNewGroupCredentials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNewGroupCredentialsActionPerformed(evt);
            }
        });

        jLabel13.setText("Panel Administratora");

        AdminButtonLogOut1.setText("Wyloguj");
        AdminButtonLogOut1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonLogOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonLogOut1ActionPerformed(evt);
            }
        });

        jButton1.setText("⃪ wróć");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminDodajGrupeLayout = new javax.swing.GroupLayout(AdminDodajGrupe);
        AdminDodajGrupe.setLayout(AdminDodajGrupeLayout);
        AdminDodajGrupeLayout.setHorizontalGroup(
            AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                .addGroup(AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AdminButtonLogOut1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sendNewGroupCredentials, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(nazwaGrupy, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminDodajGrupeLayout.setVerticalGroup(
            AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminDodajGrupeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminButtonLogOut1)
                    .addComponent(jLabel13))
                .addGap(121, 121, 121)
                .addGroup(AdminDodajGrupeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nazwaGrupy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendNewGroupCredentials)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        getContentPane().add(AdminDodajGrupe, "card7");

        AdminPrzypiszStudentaGrupie.setName("AdminPrzypiszStudentaGrupie"); // NOI18N

        jLabel14.setText("Panel Administratora");

        AdminButtonLogOut2.setText("Wyloguj");
        AdminButtonLogOut2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonLogOut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonLogOut2ActionPerformed(evt);
            }
        });

        jButton2.setText("⃪ wróć");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        listaStudentow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Przypisz ");

        jLabel16.setText("do grupy");

        listaGrup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Przypisz");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPrzypiszStudentaGrupieLayout = new javax.swing.GroupLayout(AdminPrzypiszStudentaGrupie);
        AdminPrzypiszStudentaGrupie.setLayout(AdminPrzypiszStudentaGrupieLayout);
        AdminPrzypiszStudentaGrupieLayout.setHorizontalGroup(
            AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                .addGroup(AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AdminButtonLogOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaStudentow, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(listaGrup, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AdminPrzypiszStudentaGrupieLayout.setVerticalGroup(
            AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPrzypiszStudentaGrupieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminButtonLogOut2)
                    .addComponent(jLabel14))
                .addGap(159, 159, 159)
                .addGroup(AdminPrzypiszStudentaGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaStudentow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaGrup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18))
        );

        getContentPane().add(AdminPrzypiszStudentaGrupie, "card8");

        TeacherPrzypiszEgzaminGrupie.setName("TeacherPrzypiszEgzaminGrupie"); // NOI18N

        jLabel17.setText("Panel Egzaminatora");

        AdminButtonLogOut3.setText("Wyloguj");
        AdminButtonLogOut3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AdminButtonLogOut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminButtonLogOut3ActionPerformed(evt);
            }
        });

        jButton4.setText("⃪ wróć");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        listaEgzaminow.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("Przypisz ");

        jLabel19.setText("do grupy");

        listaGrup1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Przypisz");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeacherPrzypiszEgzaminGrupieLayout = new javax.swing.GroupLayout(TeacherPrzypiszEgzaminGrupie);
        TeacherPrzypiszEgzaminGrupie.setLayout(TeacherPrzypiszEgzaminGrupieLayout);
        TeacherPrzypiszEgzaminGrupieLayout.setHorizontalGroup(
            TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AdminButtonLogOut3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listaEgzaminow, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(listaGrup1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TeacherPrzypiszEgzaminGrupieLayout.setVerticalGroup(
            TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminButtonLogOut3)
                    .addComponent(jLabel17))
                .addGap(159, 159, 159)
                .addGroup(TeacherPrzypiszEgzaminGrupieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaEgzaminow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaGrup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );

        getContentPane().add(TeacherPrzypiszEgzaminGrupie, "card8");

        StudentWyniki.setName("StudentWyniki"); // NOI18N

        jLabel20.setText("Panel Studenta");

        jButton6.setText("⃪ wróć");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ListaWynikiEgzaminow.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaWynikiEgzaminow);

        jLabel21.setText("Twoje wyniki:");

        javax.swing.GroupLayout StudentWynikiLayout = new javax.swing.GroupLayout(StudentWyniki);
        StudentWyniki.setLayout(StudentWynikiLayout);
        StudentWynikiLayout.setHorizontalGroup(
            StudentWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentWynikiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(StudentWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(651, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentWynikiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StudentWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );
        StudentWynikiLayout.setVerticalGroup(
            StudentWynikiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentWynikiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addGap(20, 20, 20)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(23, 23, 23))
        );

        getContentPane().add(StudentWyniki, "card10");

        TeacherWynikiStudentow.setName("TeacherWynikiStudentow"); // NOI18N

        jLabel22.setText("Panel Egzaminatora");

        jButton7.setText("⃪ wróć");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        ListaWynikiEgzaminow1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaWynikiEgzaminow1);

        jLabel23.setText("Wyniki studentow:");

        javax.swing.GroupLayout TeacherWynikiStudentowLayout = new javax.swing.GroupLayout(TeacherWynikiStudentow);
        TeacherWynikiStudentow.setLayout(TeacherWynikiStudentowLayout);
        TeacherWynikiStudentowLayout.setHorizontalGroup(
            TeacherWynikiStudentowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherWynikiStudentowLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TeacherWynikiStudentowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(620, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherWynikiStudentowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TeacherWynikiStudentowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );
        TeacherWynikiStudentowLayout.setVerticalGroup(
            TeacherWynikiStudentowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherWynikiStudentowLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addGap(20, 20, 20)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(23, 23, 23))
        );

        getContentPane().add(TeacherWynikiStudentow, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logINButtonActionPerformed
        LoginPage.logIn(this);
    }//GEN-LAST:event_logINButtonActionPerformed

    private void choosePanelButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePanelButtonAdminActionPerformed
        showPanel("AdminPanel");
    }//GEN-LAST:event_choosePanelButtonAdminActionPerformed

    private void StudentButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonLogOutActionPerformed
        System.out.println(rola.logOut());
        showPanel("LoginPanel");
    }//GEN-LAST:event_StudentButtonLogOutActionPerformed

    private void TeacherButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonLogOutActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_TeacherButtonLogOutActionPerformed

    private void AdminButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonLogOutActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_AdminButtonLogOutActionPerformed

    private void choosePanelButtonTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePanelButtonTeacherActionPerformed
        showPanel("TeacherPanel");
    }//GEN-LAST:event_choosePanelButtonTeacherActionPerformed

    private void StudentButtonDoExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonDoExamActionPerformed
        JOptionPane.showMessageDialog(this, "Funkcjonalnosc dostepna w kolejnych wersjach systemu.");
    }//GEN-LAST:event_StudentButtonDoExamActionPerformed

    private void StudentButtonCheckResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentButtonCheckResultsActionPerformed
        showPanel("StudentWyniki");
        Student.checkResults();
    }//GEN-LAST:event_StudentButtonCheckResultsActionPerformed

    private void TeacherButtonAddExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonAddExamActionPerformed
        JOptionPane.showMessageDialog(this, "Funkcjonalnosc dostepna w kolejnych wersjach systemu.");
    }//GEN-LAST:event_TeacherButtonAddExamActionPerformed

    private void TeacherButtonCheckAnswearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonCheckAnswearsActionPerformed
        JOptionPane.showMessageDialog(this, "Funkcjonalnosc dostepna w kolejnych wersjach systemu.");
    }//GEN-LAST:event_TeacherButtonCheckAnswearsActionPerformed

    private void TeacherButtonAssignExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonAssignExamActionPerformed
        showPanel("TeacherPrzypiszEgzaminGrupie");
        Teacher.prepareAssignmentPanel();
    }//GEN-LAST:event_TeacherButtonAssignExamActionPerformed

    private void TeacherButtonViewAnswearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherButtonViewAnswearsActionPerformed
        showPanel("TeacherWynikiStudentow");
        Teacher.viewAnswears();
    }//GEN-LAST:event_TeacherButtonViewAnswearsActionPerformed

    private void AdminButtonAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAddGroupActionPerformed
        showPanel("adminDodajGrupe");
    }//GEN-LAST:event_AdminButtonAddGroupActionPerformed

    private void AdminButtonAssignStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonAssignStudentActionPerformed
        showPanel("AdminPrzypiszStudentaGrupie");
        Administrator.prepareAssignmentPanel();
    }//GEN-LAST:event_AdminButtonAssignStudentActionPerformed

    private void AdminButtonLogOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonLogOut1ActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_AdminButtonLogOut1ActionPerformed

    private void sendNewGroupCredentialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNewGroupCredentialsActionPerformed
        Administrator.addGroup();
    }//GEN-LAST:event_sendNewGroupCredentialsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showPanel("AdminPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AdminButtonLogOut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonLogOut2ActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_AdminButtonLogOut2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showPanel("AdminPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Administrator.assignStudentToGroup();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AdminButtonLogOut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminButtonLogOut3ActionPerformed
        StudentButtonLogOutActionPerformed(evt);
    }//GEN-LAST:event_AdminButtonLogOut3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        showPanel("TeacherPanel");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Teacher.assignExamToGroup();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        showPanel("StudentPanel");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        showPanel("TeacherPanel");
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     *  Metoda main. Tworzy nowy wątek, w którym pracuje GUI.
     * 
     *  @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ApplicationFrame().setVisible(true);
        });
    }
    
    /**
     * Ustawia widoczność panelu przekazanego w argumencie na true, reszty na false. 
     * 
     * @param name String: nazwa panelu.
     */
    public void showPanel(String name){
        Component[] comp = getContentPane().getComponents();
        
        for(Component c : comp ){
            if ( c.getName().equals(name) ) 
                c.setVisible(true);
            else
                c.setVisible(false);
        }
    }
    
    /**
     *  Metoda do inicjalizowania zmiennej 'role'.
     * 
     * @param p     Parametr typu 'Person': rola uzytkownika po zalogowaniu.
     */
    public void setRole(Person p){
        rola = p;
    }
    
    /**
     *  Metoda pobierania adresu IP serwera wpisanego w formularzu logowania.
     * 
     *  @return     String: adres IP serwera.
     */
    public String getServerAddr(){
        return serverAddress.getText();
    }

    /**
     *  Metoda do pobierania loginu wpisanego w formularzu logowania.
     * 
     * @return  String: login wpisany w formularzu logowania.
     */
    public String getLogin() {
        return login.getText();
    }

    /**
     *  Metoda do pobierania hasla wpisanego w formularzu logowania.
     * 
     * @return  String: haslo wpisane w formularzu logowania.
     */
    public String getPassword() {
        return password.getText();
    }

    /**
     *  Metoda do pobierania numeru portu serwera wpisanego w formularzu logowania.
     * 
     *  @return     String: port wpisany w formularzu logowania.
     */
    public String getServerPort() {
        return serverPort.getText();
    }
    
    /**
     *  Metoda do pobierania nazwy grupy wybranej z selecta na formularzu nauczyciela.
     * 
     * @return  String: nazwa grupy wybranej przez uzytkownika.
     */
    public String getNewGroupName(){
        return nazwaGrupy.getText();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminButtonAddGroup;
    private javax.swing.JButton AdminButtonAssignStudent;
    private javax.swing.JButton AdminButtonLogOut;
    private javax.swing.JButton AdminButtonLogOut1;
    private javax.swing.JButton AdminButtonLogOut2;
    private javax.swing.JButton AdminButtonLogOut3;
    private javax.swing.JPanel AdminDodajGrupe;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel AdminPrzypiszStudentaGrupie;
    public javax.swing.JList<String> ListaWynikiEgzaminow;
    public javax.swing.JList<String> ListaWynikiEgzaminow1;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton StudentButtonCheckResults;
    private javax.swing.JButton StudentButtonDoExam;
    private javax.swing.JButton StudentButtonLogOut;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JPanel StudentWyniki;
    private javax.swing.JButton TeacherButtonAddExam;
    private javax.swing.JButton TeacherButtonAssignExam;
    private javax.swing.JButton TeacherButtonCheckAnswears;
    private javax.swing.JButton TeacherButtonLogOut;
    private javax.swing.JButton TeacherButtonViewAnswears;
    private javax.swing.JPanel TeacherPanel;
    private javax.swing.JPanel TeacherPrzypiszEgzaminGrupie;
    private javax.swing.JPanel TeacherWynikiStudentow;
    private javax.swing.JButton choosePanelButtonAdmin;
    private javax.swing.JButton choosePanelButtonTeacher;
    private javax.swing.JPanel chooseRolePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> listaEgzaminow;
    public javax.swing.JComboBox<String> listaGrup;
    public javax.swing.JComboBox<String> listaGrup1;
    public javax.swing.JComboBox<String> listaStudentow;
    private javax.swing.JButton logINButton;
    private javax.swing.JTextField login;
    private javax.swing.JTextField nazwaGrupy;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton sendNewGroupCredentials;
    private javax.swing.JTextField serverAddress;
    private javax.swing.JTextField serverPort;
    // End of variables declaration//GEN-END:variables
}
